version: '3.7'
services:
  pastec:
    build:
      context: .
    ports:
      - '4212:4212'
    restart: always
    #volumes:
    #  - ./pastec-index:/pastec/data:rw  # Ensures data directory is correctly mapped for index files
    command: /bin/sh -c "cd /pastec/build && ./pastec -p 4212 /pastec/data/visualWordsORB.dat"